version: '3.8'

services:
  # 1. The Database Container
  db:
    image: postgres:15
    container_name: poker_db
    environment:
      - POSTGRES_USER=mlflow_user
      - POSTGRES_PASSWORD=mlflow_password
      - POSTGRES_DB=mlflow_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # 2. The MLflow Tracking Server Container
  mlflow:
    build: .
    container_name: poker_mlflow
    ports:
      - "5000:5000"
    command: >
      mlflow server
      --backend-store-uri postgresql://mlflow_user:mlflow_password@db:5432/mlflow_db
      --default-artifact-root /mlflow/artifacts
      --host 0.0.0.0
    depends_on:
      - db
    volumes:
      - mlflow_artifacts:/mlflow/artifacts

  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: poker_api
    ports:
      - "8000:8000"
    depends_on:
      - mlflow
volumes:
  postgres_data:
  mlflow_artifacts: